# Generated by Django 5.0.7 on 2024-08-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="driver",
            new_name="id_driver",
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="rider",
            new_name="id_rider",
        ),
    ]
